---

- name: Install nginx
  apt: name={{ nginx_package }} state=present
  tags:
    - nginx

- name: Disable nginx default website
  file: path=/etc/nginx/sites-enabled/default state=absent
  when: nginx_disable_default_site
  notify:
    - restart nginx
  tags:
    - nginx

- name: Copy SSL configuration
  template: src=ssl.conf.j2 dest=/etc/nginx/conf.d/ssl.conf
  notify:
    - restart nginx
  tags:
    - nginx
    - ssl

- name: Copy firewall configuration
  template: src=firewall.conf.j2 dest=/etc/nginx/firewall.conf
  notify:
    - restart nginx
  tags:
    - nginx
    - firewall

- include: logstash.yml
